=== SafePolyMed-UdS/precisiondosing-api-go/api/schemas/precheck_input.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "patient_id": {
      "type": "integer",
      "description": "A unique identifier for the patient."
    },
    "patient_characteristics": {
      "type": "object",
      "properties": {
        "age": {
          "type": "integer",
          "description": "The patient's age in years.",
          "minimum": 18,
          "maximum": 100,
          "examples": [
            18,
            40,
            64
          ]
        },
        "weight": {
          "type": "number",
          "description": "The patient's weight in kilograms.",
          "minimum": 40,
          "maximum": 200,
          "examples": [
            50,
            70,
            90
          ]
        },
        "height": {
          "type": "integer",
          "description": "The patient's height in centimeters.",
          "minimum": 140,
          "maximum": 200,
          "examples": [
            150,
            170,
            190
          ]
        },
        "sex": {
          "type": "string",
          "description": "The patient's sex.",
          "enum": [
            "male",
            "female",
            "unknown"
          ],
          "examples": [
            "male",
            "female",
            "unknown"
          ]
        },
        "ethnicity": {
          "type": "string",
          "description": "The patient's ethnicity.",
          "enum": [
            "european",
            "white american",
            "black american",
            "mexican",
            "asian",
            "japanese",
            "other",
            "unknown"
          ],
          "examples": [
            "european",
            "japanese",
            "other"
          ],
          "nullable": true
        },
        "kidney_disease": {
          "type": "boolean",
          "description": "Indicates if the patient has kidney disease. Only true or false values are accepted.",
          "examples": [
            true,
            false
          ]
        },
        "liver_disease": {
          "type": "boolean",
          "description": "Indicates if the patient has liver disease. Only true or false values are accepted.",
          "examples": [
            true,
            false
          ]
        }
      },
      "required": [
        "age",
        "weight",
        "height",
        "sex",
        "kidney_disease",
        "liver_disease"
      ],
      "description": "Characteristics detailing the patient's health and demographic profile."
    },
    "patient_pgx_profile": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "gene": {
            "type": "string",
            "description": "Gene of interest in pharmacogenomics.",
            "minLength": 1,
            "examples": [
              "CYP2D6",
              "CYP2C19",
              "VKORC1",
              "TPMT"
            ]
          },
          "allele1": {
            "type": "string",
            "description": "First allele variant.",
            "minLength": 2,
            "pattern": "^\\*([0-9]+)([A-Za-z]*)([0-9]*)$",
            "examples": [
              "*1",
              "*3",
              "*17"
            ]
          },
          "allele1_cnv_multiplier": {
            "type": "integer",
            "description": "Copy number variation multiplier for allele1.",
            "minimum": 1,
            "maximum": 100,
            "examples": [
              1,
              2,
              3
            ]
          },
          "allele2": {
            "type": "string",
            "description": "Second allele variant.",
            "minLength": 2,
            "pattern": "^\\*([0-9]+)([A-Za-z]*)([0-9]*)$",
            "examples": [
              "*1",
              "*3",
              "*17"
            ]
          },
          "allele2_cnv_multiplier": {
            "type": "integer",
            "description": "Copy number variation multiplier for allele2.",
            "minimum": 1,
            "maximum": 100,
            "examples": [
              1,
              2,
              3
            ]
          }
        },
        "required": [
          "gene",
          "allele1",
          "allele1_cnv_multiplier",
          "allele2",
          "allele2_cnv_multiplier"
        ],
        "description": "A patient's pharmacogenomic profile, listing specific genes and alleles relevant to drug metabolism."
      },
      "description": "Array of pharmacogenomic profiles."
    },
    "drugs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "active_substances": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "List of active substances in the drug.",
              "minLength": 1
            },
            "minItems": 1,
            "examples": [
              [
                "paracetamol"
              ],
              [
                "ibuprofen",
                "paracetamol"
              ]
            ],
            "description": "Active substances the patient is taking."
          },
          "product": {
            "type": "object",
            "description": "Product details including name and classification.",
            "properties": {
              "product_name": {
                "type": "string",
                "minLength": 1,
                "description": "The commercial name of the product."
              },
              "atc": {
                "type": "string",
                "description": "Anatomical Therapeutic Chemical classification system code."
              },
              "formulation": {
                "type": "string",
                "description": "The formulation of the drug (e.g., tablet, syrup). Only abbreviations from ABDA (see enum) are allowed.",
                "minLength": 3,
                "maxLength": 3,
                "examples": [
                  "FTA",
                  "TAB",
                  "SUS"
                ]
              }
            }
          },
          "intake_cycle": {
            "type": "object",
            "properties": {
              "intake_mode": {
                "type": "string",
                "description": "The mode of drug intake. If `on_demand`, other fields are optional. If `regular`, other fields are required.",
                "enum": [
                  "on_demand",
                  "regular"
                ]
              },
              "starting_at": {
                "type": "string",
                "minLength": 10,
                "description": "The starting date for the intake cycle. Follows ISO 8601 format.",
                "examples": [
                  "2022-01-01T00:00:00+01:00",
                  "2022-01-01T00:00:00Z"
                ],
                "nullable": true
              },
              "frequency": {
                "type": "string",
                "description": "How often the drug is taken.",
                "enum": [
                  "daily",
                  "weekly",
                  "monthly",
                  "as_needed"
                ],
                "nullable": true
              },
              "frequency_modifier": {
                "type": "integer",
                "description": "Modifier that further specifies the frequency.",
                "minimum": 1,
                "nullable": true
              },
              "intakes": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "raw_time_str": {
                      "type": "string",
                      "description": "Human-readable string indicating the time of intake."
                    },
                    "cron": {
                      "type": "string",
                      "description": "Cron expression specifying the intake schedule.",
                      "minLength": 1,
                      "examples": [
                        "0 8 * * *",
                        "0 8,12,18 * * *"
                      ]
                    },
                    "dosage": {
                      "type": "number",
                      "description": "Amount of drug administered at each intake."
                    },
                    "dosage_unit": {
                      "type": "string",
                      "description": "Unit of dosage (e.g., pills, mg)."
                    }
                  },
                  "required": [
                    "raw_time_str",
                    "cron",
                    "dosage",
                    "dosage_unit"
                  ],
                  "description": "Details of each drug intake instance."
                },
                "description": "Schedule and details of drug intake."
              }
            },
            "required": [
              "frequency",
              "frequency_modifier",
              "intakes"
            ],
            "description": "Details of the drug intake cycle."
          }
        },
        "required": [
          "active_substances",
          "intake_cycle"
        ],
        "description": "Information about drugs the patient is currently taking."
      },
      "description": "List of drugs being administered."
    }
  },
  "required": [
    "patient_id",
    "patient_characteristics",
    "drugs"
  ],
  "additionalProperties": false,
  "description": "A comprehensive schema representing a patient's health record including personal data, pharmacogenomic profile, drug intake, and dose adaptation details."
}

=== SafePolyMed-UdS/precisiondosing-api-go/api/schemas/precheck_example.json
{
  "patient_id": 73,
  "patient_characteristics": {
    "age": 24,
    "weight": 75,
    "height": 180,
    "sex": "male",
    "ethnicity": "european",
    "kidney_disease": true,
    "liver_disease": true
  },
  "patient_pgx_profile": [
    {
      "gene": "CYP2C19",
      "allele1": "*1",
      "allele1_cnv_multiplier": 1,
      "allele2": "*3",
      "allele2_cnv_multiplier": 1
    }
  ],
  "drugs": [
    {
      "active_substances": [
        "voriconazole"
      ],
      "product": {
        "product_name": "voriconazol ratiopharm 200 mg filmtabletten",
        "atc": "J02AC03",
        "formulation": "FTA"
      },
      "intake_cycle": {
        "intake_mode": "regular",
        "starting_at": "2021-06-01T00:00:00Z",
        "frequency": "daily",
        "frequency_modifier": 2,
        "intakes": [
          {
            "raw_time_str": "08:30",
            "cron": "0 30 8 ? * *",
            "dosage": 200,
            "dosage_unit": "mg"
          },
          {
            "raw_time_str": "18:00",
            "cron": "0 0 18 ? * *",
            "dosage": 200,
            "dosage_unit": "mg"
          }
        ]
      }
    },
    {
      "active_substances": [
        "cimetidine"
      ],
      "product": {
        "product_name": "Cimetidin acis 400 mg",
        "atc": "A02BA01",
        "formulation": "FTA"
      },
      "intake_cycle": {
        "intake_mode": "regular",
        "starting_at": "2022-12-08T00:00:00Z",
        "frequency": "daily",
        "frequency_modifier": 3,
        "intakes": [
          {
            "raw_time_str": "08:30",
            "cron": "0 30 8 ? * *",
            "dosage": 400,
            "dosage_unit": "mg"
          },
          {
            "raw_time_str": "12:00",
            "cron": "0 0 12 ? * *",
            "dosage": 400,
            "dosage_unit": "mg"
          },
          {
            "raw_time_str": "18:00",
            "cron": "0 0 18 ? * *",
            "dosage": 400,
            "dosage_unit": "mg"
          }
        ]
      }
    },
    {
      "active_substances": [
        "omeprazole"
      ],
      "product": {
        "product_name": "Omeprazol AL 20 mg magensaftresistente Hartkapseln",
        "atc": "A02BC01",
        "formulation": "HKM"
      },
      "intake_cycle": {
        "intake_mode": "regular",
        "starting_at": "2024-01-05T00:00:00Z",
        "frequency": "daily",
        "frequency_modifier": 1,
        "intakes": [
          {
            "raw_time_str": "08:30",
            "cron": "0 30 8 ? * *",
            "dosage": 20,
            "dosage_unit": "mg"
          }
        ]
      }
    }
  ]
}
